using FactoryIQ.Core.Contracts; using FactoryIQ.Core.Models;
namespace FactoryIQ.Agents;
public sealed class IncidentIntakeAgent : IIncidentIntakeAgent
{ public Task<NormalizedIncident> NormalizeAsync(IncidentInput input, CancellationToken ct) { var symptoms = input.Logs.Concat(input.Telemetry.Where(kv=>kv.Value>80).Select(kv=>$"{kv.Key}={kv.Value}")).Distinct().ToArray(); var entities = new[]{"wafer-inspection-tool","sql-db","deployment-ring-a"}; return Task.FromResult(new NormalizedIncident($"FIQ-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}", input.Title, symptoms, entities, input.Telemetry, input.Severity)); } }
public sealed class IntelligenceAgent(IIQProvider iq) : IIntelligenceAgent
{ public async Task<IReadOnlyList<IntelligenceFinding>> AnalyzeAsync(NormalizedIncident incident, CancellationToken ct) { var result = await iq.QueryAsync($"{incident.Title} {string.Join(' ',incident.Symptoms)}", ct); return [new IntelligenceFinding("Microsoft IQ intelligence indicates the failure pattern matches a regression in wafer image post-processing that amplifies database latency under memory pressure.", .91, [result])]; } }
public sealed class RootCauseAgent : IRootCauseAgent
{ public Task<IReadOnlyList<RootCauseHypothesis>> AnalyzeAsync(NormalizedIncident incident, IReadOnlyList<IntelligenceFinding> findings, CancellationToken ct) => Task.FromResult<IReadOnlyList<RootCauseHypothesis>>([new RootCauseHypothesis("Recent wafer inspection deployment introduced an inefficient image aggregation path, causing CPU saturation, memory pressure, and cascading database latency.", .88, "Telemetry shows CPU and memory saturation after deployment while Microsoft IQ findings identify matching prior incidents and runbook guidance.", ["Rollback deployment CHG-2026-0612", "Scale inspection workers", "Increase DB connection pool headroom", "Run memory profiling before redeploy"])]); }
public sealed class ExecutiveReportAgent : IExecutiveReportAgent
{ public Task<ExecutiveReport> CreateAsync(NormalizedIncident incident, IReadOnlyList<IntelligenceFinding> findings, IReadOnlyList<RootCauseHypothesis> causes, CancellationToken ct) => Task.FromResult(new ExecutiveReport("Wafer inspection throughput is degraded by an application regression amplified by platform resource pressure.", "Agents correlated incident symptoms, Microsoft IQ knowledge, telemetry, and change history to identify the most likely root cause.", causes[0].RecommendedActions, "Restoring the prior release protects yield, reduces engineering triage time, and limits manufacturing downtime.")); }
public sealed class IncidentAnalysisOrchestrator(IIncidentIntakeAgent intake, IIntelligenceAgent intel, IRootCauseAgent root, IExecutiveReportAgent report) : IIncidentAnalysisOrchestrator
{ public async Task<AnalysisResult> AnalyzeAsync(IncidentInput input, CancellationToken ct) { var n=await intake.NormalizeAsync(input,ct); var f=await intel.AnalyzeAsync(n,ct); var r=await root.AnalyzeAsync(n,f,ct); var e=await report.CreateAsync(n,f,r,ct); return new AnalysisResult(n,f,r,e,[new("Incident Intake Agent","Normalized incident and extracted symptoms",.95),new("Intelligence Agent","Queried Microsoft IQ abstraction and correlated findings",.91),new("Root Cause Agent","Ranked hypotheses and actions",.88),new("Executive Report Agent","Generated executive and technical report",.9)], r.Max(x=>x.Confidence)); } }
